# Generated by Django 5.0.7 on 2024-07-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_average_rating_customuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='rating',
        ),
    ]
