# Generated by Django 5.0.7 on 2024-07-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customFit', '0002_recommendedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedproduct',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
