# Generated by Django 5.0.7 on 2024-07-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customFit', '0003_recommendedproduct_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedproduct',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
