# Generated by Django 5.0.7 on 2024-07-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customFit', '0004_recommendedproduct_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedproduct',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
